version: "3.9"

services:
  ecommerce-db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: demo,ecommerce
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ecommerce-db-data:/var/lib/postgresql/data
  
  ecommerce-keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak-dev
    container_name: ecommerce-keycloak
    restart: always
    volumes:
      - ./config/:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    environment:
      PROXY_ADDRESS_FORWARDING: true
    depends_on:
      - ecommerce-db

volumes:
  ecommerce-db-data: