
import { Darker_Grotesque, Kalam } from "next/font/google";
import { KeycloakProvider, TailwindThemeProvider } from "../providers";

import { dir } from "i18next";

import { localeCodes } from "@/i18n/settings";

const kalam = Kalam({ 
    subsets: ['latin'],
    weight:["400","700"],
    variable: '--font-kalam',
  });
  
const darker_grotesque =Darker_Grotesque(
{
    subsets: ['latin'],
    weight:[ "300", "400"],
    variable: '--font-darker_grotesque',
}
);

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
  return localeCodes.map((locale) => ({ locale }));
}

export default function LocaleLayout({
    children,
    params: {locale}
  }: {
    children: React.ReactNode;
    params: {locale: string};
  }) {

    return (
      <html lang={locale} dir={dir(locale)} suppressHydrationWarning>
        <body className={`${kalam.variable} ${darker_grotesque.variable}`} suppressHydrationWarning={true}>
        <TailwindThemeProvider>
        <KeycloakProvider>
          {children}
        </KeycloakProvider>
        </TailwindThemeProvider>
        
      </body>
      </html>
    );
  }