import type {Metadata} from "next";
import "@/styles/globals.css";
import { ReadonlyChildrenProps } from "@/types/childrenProps";

export const metadata : Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({children}:ReadonlyChildrenProps) {
    return (
        <html suppressHydrationWarning>
            {children}
        </html>
    );
}
