import type {Metadata} from "next";
import "@/styles/globals.css";
import {cn} from "@/lib/utils";
import {darker_grotesque} from "@/lib/font";
import {LayoutProps} from "@/types/layoutProps";
import {languages} from "@/lib/i18n/settings";
import {ThemeProvider} from "@/provider/theme-provider";
import { dir } from "i18next";

export async function generateStaticParams() {
    return languages.map((lng) => ({lng}));
}

export const metadata : Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function BodyLayout({children, params: {
        lng
    }} : LayoutProps) {
    return (
            <body
                suppressHydrationWarning
                lang={lng}
                dir={dir(lng)}
                className={cn("min-h-screen bg-white dark:bg-neutral-800 font-darker_grotesque antialiased overflow-y-hidden", darker_grotesque.variable)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange={false}>
                    {children}
                </ThemeProvider>
            </body>
    );
}
